SOP_CATALOG = [
    # ── GMP Manufacturing (15 SOPs) ──────────────────────────────────────────
    {
        "sop_number": "SOP-GMP-001",
        "title": "Equipment Cleaning and Sanitization Procedure",
        "domain": "GMP",
        "version": "2.3",
        "effective_date": "2023-04-01",
        "supersedes_version": "2.2",
        "approver": "Dr. Margaret Chen, VP Quality Assurance",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["cleaning validation", "sanitization", "equipment", "rinse", "contamination", "CIP", "visual inspection"],
    },
    {
        "sop_number": "SOP-GMP-002",
        "title": "Batch Record Review and Approval",
        "domain": "GMP",
        "version": "3.0",
        "effective_date": "2024-01-15",
        "supersedes_version": "2.5",
        "approver": "James Whitfield, Director of Quality Operations",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["batch record", "review", "approval", "release", "discrepancy", "reconciliation", "lot"],
    },
    {
        "sop_number": "SOP-GMP-003",
        "title": "Environmental Monitoring Program",
        "domain": "GMP",
        "version": "2.1",
        "effective_date": "2023-07-01",
        "supersedes_version": "2.0",
        "approver": "Dr. Sarah Nguyen, Quality Systems Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["environmental monitoring", "microbial", "cleanroom", "action limit", "alert limit", "viable", "non-viable"],
    },
    {
        "sop_number": "SOP-GMP-004",
        "title": "Deviation Management and Reporting",
        "domain": "GMP",
        "version": "2.4",
        "effective_date": "2023-09-01",
        "supersedes_version": "2.3",
        "approver": "Robert Harmon, Quality Assurance Director",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["deviation", "incident", "investigation", "CAPA", "root cause", "impact assessment", "closure"],
    },
    {
        "sop_number": "SOP-GMP-005",
        "title": "Corrective and Preventive Action (CAPA) System",
        "domain": "GMP",
        "version": "2.2",
        "effective_date": "2023-06-15",
        "supersedes_version": "2.1",
        "approver": "Dr. Margaret Chen, VP Quality Assurance",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["CAPA", "corrective action", "preventive action", "effectiveness check", "root cause analysis", "trending", "verification"],
    },
    {
        "sop_number": "SOP-GMP-006",
        "title": "Change Control Management",
        "domain": "GMP",
        "version": "2.5",
        "effective_date": "2023-11-01",
        "supersedes_version": "2.4",
        "approver": "James Whitfield, Director of Quality Operations",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["change control", "change request", "impact assessment", "validation", "regulatory", "change category", "approval"],
    },
    {
        "sop_number": "SOP-GMP-007",
        "title": "Label Reconciliation and Issuance",
        "domain": "GMP",
        "version": "2.1",
        "effective_date": "2023-03-01",
        "supersedes_version": "2.0",
        "approver": "Dr. Sarah Nguyen, Quality Systems Manager",
        "section_count": 9,
        "page_estimate": 10,
        "keywords": ["label", "reconciliation", "issuance", "count", "destruction", "label control", "discrepancy"],
    },
    {
        "sop_number": "SOP-GMP-008",
        "title": "Yield Calculation and Reconciliation",
        "domain": "GMP",
        "version": "2.2",
        "effective_date": "2023-05-01",
        "supersedes_version": "2.1",
        "approver": "Robert Harmon, Quality Assurance Director",
        "section_count": 9,
        "page_estimate": 10,
        "keywords": ["yield", "theoretical yield", "actual yield", "reconciliation", "process loss", "acceptance criteria", "batch"],
    },
    {
        "sop_number": "SOP-GMP-009",
        "title": "In-Process Sampling and Testing",
        "domain": "GMP",
        "version": "2.3",
        "effective_date": "2023-08-15",
        "supersedes_version": "2.2",
        "approver": "Dr. Margaret Chen, VP Quality Assurance",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["in-process", "sampling", "testing", "specification", "acceptance criteria", "IPC", "frequency"],
    },
    {
        "sop_number": "SOP-GMP-010",
        "title": "Contamination Prevention and Control",
        "domain": "GMP",
        "version": "2.4",
        "effective_date": "2024-02-01",
        "supersedes_version": "2.3",
        "approver": "James Whitfield, Director of Quality Operations",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["contamination", "cross-contamination", "microbiological", "particulate", "prevention", "control", "segregation"],
    },
    {
        "sop_number": "SOP-GMP-011",
        "title": "Personnel Gowning Procedure for Cleanroom Entry",
        "domain": "GMP",
        "version": "2.2",
        "effective_date": "2023-10-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Sarah Nguyen, Quality Systems Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["gowning", "cleanroom", "aseptic", "garment", "donning", "doffing", "airlock"],
    },
    {
        "sop_number": "SOP-GMP-012",
        "title": "Water System Monitoring and Control",
        "domain": "GMP",
        "version": "2.3",
        "effective_date": "2023-12-01",
        "supersedes_version": "2.2",
        "approver": "Robert Harmon, Quality Assurance Director",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["purified water", "WFI", "TOC", "conductivity", "bioburden", "alert limit", "action limit"],
    },
    {
        "sop_number": "SOP-GMP-013",
        "title": "Compressed Gas Testing and Certification",
        "domain": "GMP",
        "version": "2.1",
        "effective_date": "2023-04-15",
        "supersedes_version": "2.0",
        "approver": "Dr. Margaret Chen, VP Quality Assurance",
        "section_count": 9,
        "page_estimate": 10,
        "keywords": ["compressed gas", "nitrogen", "carbon dioxide", "purity", "moisture", "oil content", "certificate of analysis"],
    },
    {
        "sop_number": "SOP-GMP-014",
        "title": "Area Clearance and Line Clearance Verification",
        "domain": "GMP",
        "version": "2.2",
        "effective_date": "2023-07-15",
        "supersedes_version": "2.1",
        "approver": "James Whitfield, Director of Quality Operations",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["line clearance", "area clearance", "changeover", "product removal", "verification", "checklist", "cross-contamination"],
    },
    {
        "sop_number": "SOP-GMP-015",
        "title": "Finished Goods Release and Disposition",
        "domain": "GMP",
        "version": "2.5",
        "effective_date": "2024-03-01",
        "supersedes_version": "2.4",
        "approver": "Dr. Sarah Nguyen, Quality Systems Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["release", "disposition", "approved", "rejected", "quarantine", "Qualified Person", "certificate of analysis"],
    },
    # ── GCP Clinical Trials (10 SOPs) ────────────────────────────────────────
    {
        "sop_number": "SOP-GCP-001",
        "title": "Informed Consent Process and Documentation",
        "domain": "GCP",
        "version": "2.3",
        "effective_date": "2023-05-01",
        "supersedes_version": "2.2",
        "approver": "Dr. Linda Okonkwo, Head of Clinical Operations",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["informed consent", "ICF", "subject", "voluntarily", "re-consent", "capacity", "documentation"],
    },
    {
        "sop_number": "SOP-GCP-002",
        "title": "Adverse Event and Serious Adverse Event Reporting",
        "domain": "GCP",
        "version": "2.4",
        "effective_date": "2023-09-15",
        "supersedes_version": "2.3",
        "approver": "Thomas Brecker, Clinical Quality Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["adverse event", "SAE", "causality", "reporting", "expedited", "MedWatch", "E2A"],
    },
    {
        "sop_number": "SOP-GCP-003",
        "title": "Protocol Deviation Management",
        "domain": "GCP",
        "version": "2.2",
        "effective_date": "2023-06-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Linda Okonkwo, Head of Clinical Operations",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["protocol deviation", "protocol violation", "major deviation", "minor deviation", "reporting", "waiver", "IRB notification"],
    },
    {
        "sop_number": "SOP-GCP-004",
        "title": "Investigational Product Accountability",
        "domain": "GCP",
        "version": "2.3",
        "effective_date": "2023-08-01",
        "supersedes_version": "2.2",
        "approver": "Thomas Brecker, Clinical Quality Manager",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["investigational product", "IP accountability", "dispensing", "returns", "destruction", "drug log", "reconciliation"],
    },
    {
        "sop_number": "SOP-GCP-005",
        "title": "Source Data Verification and Quality Review",
        "domain": "GCP",
        "version": "2.1",
        "effective_date": "2023-04-01",
        "supersedes_version": "2.0",
        "approver": "Dr. Linda Okonkwo, Head of Clinical Operations",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["source data", "SDV", "monitoring", "CRF", "original record", "transcription", "query"],
    },
    {
        "sop_number": "SOP-GCP-006",
        "title": "Site Initiation Visit Conduct",
        "domain": "GCP",
        "version": "2.2",
        "effective_date": "2023-10-01",
        "supersedes_version": "2.1",
        "approver": "Thomas Brecker, Clinical Quality Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["site initiation", "SIV", "investigator", "training", "delegation log", "trial master file", "start-up"],
    },
    {
        "sop_number": "SOP-GCP-007",
        "title": "Randomization and Blinding Procedures",
        "domain": "GCP",
        "version": "2.2",
        "effective_date": "2023-07-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Linda Okonkwo, Head of Clinical Operations",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["randomization", "blinding", "unblinding", "emergency unblinding", "allocation", "stratification", "IWRS"],
    },
    {
        "sop_number": "SOP-GCP-008",
        "title": "IRB/IEC Submission and Approval Management",
        "domain": "GCP",
        "version": "2.1",
        "effective_date": "2023-03-15",
        "supersedes_version": "2.0",
        "approver": "Thomas Brecker, Clinical Quality Manager",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["IRB", "IEC", "ethics committee", "approval", "amendment", "continuing review", "submission"],
    },
    {
        "sop_number": "SOP-GCP-009",
        "title": "Trial Master File Maintenance and Archiving",
        "domain": "GCP",
        "version": "2.3",
        "effective_date": "2023-11-01",
        "supersedes_version": "2.2",
        "approver": "Dr. Linda Okonkwo, Head of Clinical Operations",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["TMF", "trial master file", "eTMF", "archiving", "inspection readiness", "completeness", "ICH E6"],
    },
    {
        "sop_number": "SOP-GCP-010",
        "title": "Clinical Site Monitoring and Close-Out",
        "domain": "GCP",
        "version": "2.2",
        "effective_date": "2024-01-01",
        "supersedes_version": "2.1",
        "approver": "Thomas Brecker, Clinical Quality Manager",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["site monitoring", "close-out", "COV", "monitoring report", "findings", "CAPA", "reconciliation"],
    },
    # ── GLP Laboratory Operations (10 SOPs) ──────────────────────────────────
    {
        "sop_number": "SOP-GLP-001",
        "title": "Instrument Calibration and Qualification",
        "domain": "GLP",
        "version": "2.3",
        "effective_date": "2023-06-01",
        "supersedes_version": "2.2",
        "approver": "Dr. Patricia Yuen, Laboratory Director",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["calibration", "qualification", "IQ", "OQ", "PQ", "tolerance", "traceability"],
    },
    {
        "sop_number": "SOP-GLP-002",
        "title": "Reagent and Solution Preparation",
        "domain": "GLP",
        "version": "2.1",
        "effective_date": "2023-04-01",
        "supersedes_version": "2.0",
        "approver": "Kevin Marsh, Quality Control Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["reagent", "solution preparation", "expiry", "labeling", "stability", "reference material", "preparation record"],
    },
    {
        "sop_number": "SOP-GLP-003",
        "title": "Sample Receipt, Logging, and Chain of Custody",
        "domain": "GLP",
        "version": "2.2",
        "effective_date": "2023-08-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Patricia Yuen, Laboratory Director",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["sample receipt", "chain of custody", "LIMS", "condition assessment", "sample ID", "storage", "integrity"],
    },
    {
        "sop_number": "SOP-GLP-004",
        "title": "Laboratory Data Recording and Raw Data Management",
        "domain": "GLP",
        "version": "2.4",
        "effective_date": "2023-10-15",
        "supersedes_version": "2.3",
        "approver": "Kevin Marsh, Quality Control Manager",
        "section_count": 12,
        "page_estimate": 13,
        "keywords": ["data recording", "raw data", "laboratory notebook", "corrections", "attributable", "legible", "contemporaneous"],
    },
    {
        "sop_number": "SOP-GLP-005",
        "title": "Reference Standard Management and Certification",
        "domain": "GLP",
        "version": "2.2",
        "effective_date": "2023-05-15",
        "supersedes_version": "2.1",
        "approver": "Dr. Patricia Yuen, Laboratory Director",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["reference standard", "primary standard", "working standard", "certification", "potency", "storage", "requalification"],
    },
    {
        "sop_number": "SOP-GLP-006",
        "title": "Test Method Validation",
        "domain": "GLP",
        "version": "2.3",
        "effective_date": "2023-09-01",
        "supersedes_version": "2.2",
        "approver": "Kevin Marsh, Quality Control Manager",
        "section_count": 13,
        "page_estimate": 15,
        "keywords": ["method validation", "accuracy", "precision", "linearity", "specificity", "LOQ", "ICH Q2(R1)"],
    },
    {
        "sop_number": "SOP-GLP-007",
        "title": "Laboratory Notebook Management",
        "domain": "GLP",
        "version": "2.1",
        "effective_date": "2023-03-01",
        "supersedes_version": "2.0",
        "approver": "Dr. Patricia Yuen, Laboratory Director",
        "section_count": 9,
        "page_estimate": 10,
        "keywords": ["laboratory notebook", "ELN", "witnessing", "pagination", "error correction", "archiving", "issuance"],
    },
    {
        "sop_number": "SOP-GLP-008",
        "title": "Quality Control Sample Management",
        "domain": "GLP",
        "version": "2.2",
        "effective_date": "2023-07-15",
        "supersedes_version": "2.1",
        "approver": "Kevin Marsh, Quality Control Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["QC samples", "control chart", "Westgard rules", "acceptance criteria", "precision", "inter-day", "intra-day"],
    },
    {
        "sop_number": "SOP-GLP-009",
        "title": "Out-of-Specification (OOS) Investigation",
        "domain": "GLP",
        "version": "2.5",
        "effective_date": "2024-02-01",
        "supersedes_version": "2.4",
        "approver": "Dr. Patricia Yuen, Laboratory Director",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["OOS", "out-of-specification", "Phase I", "Phase II", "laboratory investigation", "assignable cause", "retesting"],
    },
    {
        "sop_number": "SOP-GLP-010",
        "title": "Laboratory Records Archiving and Retention",
        "domain": "GLP",
        "version": "2.1",
        "effective_date": "2023-11-15",
        "supersedes_version": "2.0",
        "approver": "Kevin Marsh, Quality Control Manager",
        "section_count": 9,
        "page_estimate": 10,
        "keywords": ["archiving", "retention", "records management", "retrieval", "destruction", "electronic records", "21 CFR Part 11"],
    },
    # ── Pharmacovigilance (8 SOPs) ────────────────────────────────────────────
    {
        "sop_number": "SOP-PV-001",
        "title": "Suspected Unexpected Serious Adverse Reaction (SUSAR) Reporting",
        "domain": "PV",
        "version": "2.4",
        "effective_date": "2023-07-01",
        "supersedes_version": "2.3",
        "approver": "Dr. Amanda Foster, Head of Pharmacovigilance",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["SUSAR", "unexpected", "serious", "IND safety report", "15-day expedited", "EudraVigilance", "CIOMS"],
    },
    {
        "sop_number": "SOP-PV-002",
        "title": "Periodic Safety Update Report (PSUR) Preparation",
        "domain": "PV",
        "version": "2.3",
        "effective_date": "2023-09-01",
        "supersedes_version": "2.2",
        "approver": "Carl Reinhardt, PV Operations Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["PSUR", "PBRER", "benefit-risk", "cumulative", "International Birth Date", "PSUR schedule", "ICH E2C"],
    },
    {
        "sop_number": "SOP-PV-003",
        "title": "Signal Detection and Evaluation",
        "domain": "PV",
        "version": "2.2",
        "effective_date": "2023-05-15",
        "supersedes_version": "2.1",
        "approver": "Dr. Amanda Foster, Head of Pharmacovigilance",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["signal detection", "disproportionality analysis", "PRR", "ROR", "EBGM", "signal validation", "signal prioritization"],
    },
    {
        "sop_number": "SOP-PV-004",
        "title": "Literature Monitoring and Screening",
        "domain": "PV",
        "version": "2.1",
        "effective_date": "2023-04-01",
        "supersedes_version": "2.0",
        "approver": "Carl Reinhardt, PV Operations Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["literature monitoring", "PubMed", "systematic search", "individual case", "publication", "adverse event", "screening"],
    },
    {
        "sop_number": "SOP-PV-005",
        "title": "Aggregate Safety Reporting and DSUR Preparation",
        "domain": "PV",
        "version": "2.2",
        "effective_date": "2023-08-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Amanda Foster, Head of Pharmacovigilance",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["DSUR", "aggregate reporting", "investigational study", "benefit-risk", "annual report", "ICH E2F", "cumulative data"],
    },
    {
        "sop_number": "SOP-PV-006",
        "title": "Individual Case Safety Report (ICSR) Processing",
        "domain": "PV",
        "version": "2.3",
        "effective_date": "2023-10-01",
        "supersedes_version": "2.2",
        "approver": "Carl Reinhardt, PV Operations Manager",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["ICSR", "case processing", "triage", "causality assessment", "seriousness", "expectedness", "E2B"],
    },
    {
        "sop_number": "SOP-PV-007",
        "title": "MedDRA Coding and Terminology Management",
        "domain": "PV",
        "version": "2.1",
        "effective_date": "2023-06-01",
        "supersedes_version": "2.0",
        "approver": "Dr. Amanda Foster, Head of Pharmacovigilance",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["MedDRA", "preferred term", "system organ class", "LLT", "coding", "SMQ", "terminology"],
    },
    {
        "sop_number": "SOP-PV-008",
        "title": "Risk Management Plan (RMP) Development and Maintenance",
        "domain": "PV",
        "version": "2.2",
        "effective_date": "2023-12-01",
        "supersedes_version": "2.1",
        "approver": "Carl Reinhardt, PV Operations Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["risk management plan", "RMP", "important identified risk", "additional pharmacovigilance", "risk minimization", "EU RMP", "GVP"],
    },
    # ── Data Integrity (7 SOPs) ───────────────────────────────────────────────
    {
        "sop_number": "SOP-DI-001",
        "title": "Audit Trail Review and Verification",
        "domain": "DI",
        "version": "2.3",
        "effective_date": "2023-08-15",
        "supersedes_version": "2.2",
        "approver": "Dr. Francesca Lim, Data Integrity Officer",
        "section_count": 11,
        "page_estimate": 12,
        "keywords": ["audit trail", "metadata", "review", "computer system", "data change", "21 CFR Part 11", "attributable"],
    },
    {
        "sop_number": "SOP-DI-002",
        "title": "Electronic Records Management and Control",
        "domain": "DI",
        "version": "2.2",
        "effective_date": "2023-06-01",
        "supersedes_version": "2.1",
        "approver": "Steven Park, IT Compliance Manager",
        "section_count": 11,
        "page_estimate": 13,
        "keywords": ["electronic records", "21 CFR Part 11", "EMA Annex 11", "e-signature", "authentication", "record lifecycle", "migration"],
    },
    {
        "sop_number": "SOP-DI-003",
        "title": "System Access Control and User Management",
        "domain": "DI",
        "version": "2.2",
        "effective_date": "2023-09-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Francesca Lim, Data Integrity Officer",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["access control", "user management", "role-based", "privilege", "password", "authorization", "account review"],
    },
    {
        "sop_number": "SOP-DI-004",
        "title": "Backup, Recovery, and Business Continuity for GxP Systems",
        "domain": "DI",
        "version": "2.1",
        "effective_date": "2023-05-01",
        "supersedes_version": "2.0",
        "approver": "Steven Park, IT Compliance Manager",
        "section_count": 10,
        "page_estimate": 11,
        "keywords": ["backup", "recovery", "disaster recovery", "RTO", "RPO", "restoration", "verification"],
    },
    {
        "sop_number": "SOP-DI-005",
        "title": "Metadata Management and Integrity",
        "domain": "DI",
        "version": "2.2",
        "effective_date": "2023-11-01",
        "supersedes_version": "2.1",
        "approver": "Dr. Francesca Lim, Data Integrity Officer",
        "section_count": 10,
        "page_estimate": 12,
        "keywords": ["metadata", "timestamp", "user ID", "original value", "data context", "system-generated", "traceability"],
    },
    {
        "sop_number": "SOP-DI-006",
        "title": "ALCOA+ Data Integrity Compliance Framework",
        "domain": "DI",
        "version": "2.4",
        "effective_date": "2024-01-01",
        "supersedes_version": "2.3",
        "approver": "Steven Park, IT Compliance Manager",
        "section_count": 12,
        "page_estimate": 14,
        "keywords": ["ALCOA+", "attributable", "legible", "contemporaneous", "original", "accurate", "complete"],
    },
    {
        "sop_number": "SOP-DI-007",
        "title": "Computerized System Validation (CSV)",
        "domain": "DI",
        "version": "2.3",
        "effective_date": "2023-07-01",
        "supersedes_version": "2.2",
        "approver": "Dr. Francesca Lim, Data Integrity Officer",
        "section_count": 13,
        "page_estimate": 15,
        "keywords": ["computerized system validation", "CSV", "GAMP5", "validation plan", "URS", "IQ OQ PQ", "validation report"],
    },
]
