"""
Parse SOP text files into section-level chunks suitable for embedding.
Handles Markdown-formatted SOPs generated by Claude (## 1.0 / ### 1.1 headers).
"""
import re
from pathlib import Path
from typing import Optional

MIN_CHUNK_SIZE = 100
MAX_CHUNK_SIZE = 1200
OVERLAP_SIZE = 100

# Only match lines that START with one or more # marks followed by a section number.
# This avoids false matches inside tables, plain paragraphs, etc.
# Matches: "## 4.0 EQUIPMENT CLEANING" or "### 4.3 Gross Cleaning"
MARKDOWN_SECTION = re.compile(r"^(#{1,4})\s+(?:(\d+\.\d*)\s+)?(.+)$")


def _parse_header(line: str) -> Optional[tuple[str, str]]:
    """Return (section_number, section_title) if line is a Markdown section header."""
    m = MARKDOWN_SECTION.match(line.strip())
    if not m:
        return None
    num = m.group(2).rstrip(".") if m.group(2) else "0"  # "4.0" stays "4.0"; unnumbered → "0"
    title = m.group(3).strip()
    return num, title


def _clean_text(lines: list[str]) -> str:
    """Strip Markdown noise while keeping substantive content."""
    out = []
    for ln in lines:
        s = ln.strip()
        # Skip purely decorative lines
        if s in ("---", "===", "```", "~~~", ""):
            continue
        # Collapse horizontal rules
        if re.fullmatch(r"[─═\-=]{3,}", s):
            continue
        # Strip leading # markers but keep the text
        if s.startswith("#"):
            out.append(s.lstrip("#").strip())
        else:
            out.append(ln)
    return "\n".join(out).strip()


def _split_large_chunk(base_id: str, text: str, meta: dict, seen_ids: set) -> list[dict]:
    parts = []
    start = 0
    part_num = 1
    while start < len(text):
        end = start + MAX_CHUNK_SIZE
        segment = text[start:end]
        cid = f"{base_id}_part{part_num}"
        while cid in seen_ids:
            part_num += 1
            cid = f"{base_id}_part{part_num}"
        seen_ids.add(cid)
        parts.append({**meta, "chunk_id": cid, "text": segment})
        if end >= len(text):
            break
        start = end - OVERLAP_SIZE
        part_num += 1
    return parts


def parse_sop_into_chunks(sop_path: str, metadata: dict) -> list[dict]:
    content = Path(sop_path).read_text(encoding="utf-8", errors="replace")
    lines = content.splitlines()

    sop_number = metadata.get("sop_number", "UNKNOWN")
    version = metadata.get("version", "0.0")

    base_meta = {
        "sop_number": sop_number,
        "sop_title": metadata.get("title", ""),
        "version": version,
        "effective_date": metadata.get("effective_date", ""),
        "domain": metadata.get("domain", ""),
        "approver": metadata.get("approver", ""),
        "keywords": ", ".join(metadata.get("keywords", [])),
        "is_current_version": metadata.get("is_current_version", True),
    }

    # ── Split file into raw sections ─────────────────────────────────────────
    sections: list[tuple[str, str, list[str]]] = []
    cur_num: Optional[str] = None
    cur_title: Optional[str] = None
    cur_lines: list[str] = []

    for line in lines:
        parsed = _parse_header(line)
        if parsed:
            if cur_num is not None:
                sections.append((cur_num, cur_title, cur_lines))
            cur_num, cur_title = parsed
            cur_lines = [line]
        else:
            cur_lines.append(line)

    if cur_num is not None and cur_lines:
        sections.append((cur_num, cur_title, cur_lines))

    # Fallback: whole file as single chunk
    if not sections:
        text = content.strip()
        if len(text) >= MIN_CHUNK_SIZE:
            cid = f"{sop_number}_v{version}_s0"
            meta = {**base_meta, "section_number": "0", "section_title": base_meta["sop_title"]}
            if len(text) <= MAX_CHUNK_SIZE:
                return [{**meta, "chunk_id": cid, "text": text}]
            return _split_large_chunk(cid, text, meta, set())
        return []

    # ── Build chunks with deduplication ─────────────────────────────────────
    chunks: list[dict] = []
    seen_ids: set[str] = set()
    pending_text: Optional[str] = None
    pending_num: Optional[str] = None
    pending_title: Optional[str] = None

    def _make_id(num: str) -> str:
        base = f"{sop_number}_v{version}_s{num}"
        if base not in seen_ids:
            seen_ids.add(base)
            return base
        # Duplicate section number — append suffix
        i = 2
        while f"{base}_{i}" in seen_ids:
            i += 1
        seen_ids.add(f"{base}_{i}")
        return f"{base}_{i}"

    def _flush(num, title, text):
        meta = {**base_meta, "section_number": num, "section_title": title}
        cid = _make_id(num)
        if len(text) <= MAX_CHUNK_SIZE:
            chunks.append({**meta, "chunk_id": cid, "text": text})
        else:
            chunks.extend(_split_large_chunk(cid, text, meta, seen_ids))

    for sec_num, sec_title, sec_lines in sections:
        text = _clean_text(sec_lines)
        if not text:
            continue

        if len(text) < MIN_CHUNK_SIZE:
            if pending_text is not None:
                pending_text += "\n" + text
            else:
                pending_text, pending_num, pending_title = text, sec_num, sec_title
            continue

        if pending_text:
            _flush(pending_num, pending_title, pending_text + "\n" + text)
            pending_text = pending_num = pending_title = None
            continue

        _flush(sec_num, sec_title, text)

    if pending_text and len(pending_text) >= MIN_CHUNK_SIZE:
        _flush(pending_num, pending_title, pending_text)

    return chunks
